---
abstract: 'Add an x_authority key to META.yml'
author:
  - 'Tomas Doran (t0m) <bobtfish@bobtfish.net>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.05'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Module::Install::Authority
name: Module-Install-Authority
no_index:
  directory:
    - inc
    - t
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bobtfish/Module-Install-Authority.git
version: 0.03

x_authority: BOBTFISH
